name: espoir_staff_app
description: "An internal app for staff to manage attendance, view tasks, and apply for leave."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # BLoC for State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  equatable: ^2.0.5

  # Geolocation
  geolocator: ^14.0.2

  # UI & Utilities
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  uuid: ^4.5.2
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - asset/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/Espoir_Logo.png"
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "asset/Espoir_Logo_Padded.png"
  min_sdk_android: 21
